
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef HOSTNODE_H
#define HOSTNODE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 HostNode_valueRangeTest (UNS8 typeValue, void * value);
const indextable * HostNode_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data HostNode_Data;
extern UNS8 PDO181[8];		/* Mapped at index 0x2000, subindex 0x01 - 0x08 */
extern UNS8 PDO281[8];		/* Mapped at index 0x2001, subindex 0x01 - 0x08 */
extern UNS8 PDO381[8];		/* Mapped at index 0x2002, subindex 0x01 - 0x08 */
extern UNS8 PDO481[8];		/* Mapped at index 0x2003, subindex 0x01 - 0x08 */
extern UNS8 PDO182[8];		/* Mapped at index 0x2004, subindex 0x01 - 0x08 */
extern UNS8 PDO282[8];		/* Mapped at index 0x2005, subindex 0x01 - 0x08 */
extern UNS8 PDO382[8];		/* Mapped at index 0x2006, subindex 0x01 - 0x08 */
extern UNS8 PDO482[8];		/* Mapped at index 0x2007, subindex 0x01 - 0x08 */
extern UNS8 PDO183[8];		/* Mapped at index 0x2008, subindex 0x01 - 0x08 */
extern UNS8 PDO283[8];		/* Mapped at index 0x2009, subindex 0x01 - 0x08 */
extern UNS8 PDO383[8];		/* Mapped at index 0x200A, subindex 0x01 - 0x08 */
extern UNS8 PDO483[8];		/* Mapped at index 0x200B, subindex 0x01 - 0x08 */
extern UNS8 PDO184[8];		/* Mapped at index 0x200C, subindex 0x01 - 0x08 */
extern UNS8 PDO284[8];		/* Mapped at index 0x200D, subindex 0x01 - 0x08 */
extern UNS8 PDO384[8];		/* Mapped at index 0x200E, subindex 0x01 - 0x08 */
extern UNS8 PDO484[8];		/* Mapped at index 0x200F, subindex 0x01 - 0x08 */
extern UNS8 PDO185[8];		/* Mapped at index 0x2010, subindex 0x01 - 0x08 */
extern UNS8 PDO285[8];		/* Mapped at index 0x2011, subindex 0x01 - 0x08 */
extern UNS8 PDO385[8];		/* Mapped at index 0x2012, subindex 0x01 - 0x08 */
extern UNS8 PDO485[8];		/* Mapped at index 0x2013, subindex 0x01 - 0x08 */
extern UNS8 PDO186[8];		/* Mapped at index 0x2014, subindex 0x01 - 0x08 */
extern UNS8 PDO286[8];		/* Mapped at index 0x2015, subindex 0x01 - 0x08 */
extern UNS8 PDO386[8];		/* Mapped at index 0x2016, subindex 0x01 - 0x08 */
extern UNS8 PDO486[8];		/* Mapped at index 0x2017, subindex 0x01 - 0x08 */
extern UNS8 PDO187[8];		/* Mapped at index 0x2018, subindex 0x01 - 0x08 */
extern UNS8 PDO287[8];		/* Mapped at index 0x2019, subindex 0x01 - 0x08 */
extern UNS8 PDO387[8];		/* Mapped at index 0x201A, subindex 0x01 - 0x08 */
extern UNS8 PDO487[8];		/* Mapped at index 0x201B, subindex 0x01 - 0x08 */
extern UNS8 PDO188[8];		/* Mapped at index 0x201C, subindex 0x01 - 0x08 */
extern UNS8 PDO288[8];		/* Mapped at index 0x201D, subindex 0x01 - 0x08 */
extern UNS8 PDO388[8];		/* Mapped at index 0x201E, subindex 0x01 - 0x08 */
extern UNS8 PDO488[8];		/* Mapped at index 0x201F, subindex 0x01 - 0x08 */
extern UNS8 PDO189[8];		/* Mapped at index 0x2020, subindex 0x01 - 0x08 */
extern UNS8 PDO289[8];		/* Mapped at index 0x2021, subindex 0x01 - 0x08 */
extern UNS8 PDO389[8];		/* Mapped at index 0x2022, subindex 0x01 - 0x08 */
extern UNS8 PDO489[8];		/* Mapped at index 0x2023, subindex 0x01 - 0x08 */
extern UNS8 PDO18A[8];		/* Mapped at index 0x2024, subindex 0x01 - 0x08 */
extern UNS8 PDO28A[8];		/* Mapped at index 0x2025, subindex 0x01 - 0x08 */
extern UNS8 PDO38A[8];		/* Mapped at index 0x2026, subindex 0x01 - 0x08 */
extern UNS8 PDO48A[8];		/* Mapped at index 0x2027, subindex 0x01 - 0x08 */
extern UNS8 PDO18B[8];		/* Mapped at index 0x2028, subindex 0x01 - 0x08 */
extern UNS8 PDO28B[8];		/* Mapped at index 0x2029, subindex 0x01 - 0x08 */
extern UNS8 PDO38B[8];		/* Mapped at index 0x202A, subindex 0x01 - 0x08 */
extern UNS8 PDO48B[8];		/* Mapped at index 0x202B, subindex 0x01 - 0x08 */
extern UNS8 PDO18C[8];		/* Mapped at index 0x202C, subindex 0x01 - 0x08 */
extern UNS8 PDO28C[8];		/* Mapped at index 0x202D, subindex 0x01 - 0x08 */
extern UNS8 PDO38C[8];		/* Mapped at index 0x202E, subindex 0x01 - 0x08 */
extern UNS8 PDO48C[8];		/* Mapped at index 0x202F, subindex 0x01 - 0x08 */
extern UNS8 PDO18D[8];		/* Mapped at index 0x2030, subindex 0x01 - 0x08 */
extern UNS8 PDO28D[8];		/* Mapped at index 0x2031, subindex 0x01 - 0x08 */
extern UNS8 PDO38D[8];		/* Mapped at index 0x2032, subindex 0x01 - 0x08 */
extern UNS8 PDO48D[8];		/* Mapped at index 0x2033, subindex 0x01 - 0x08 */
extern UNS8 PDO18E[8];		/* Mapped at index 0x2034, subindex 0x01 - 0x08 */
extern UNS8 PDO28E[8];		/* Mapped at index 0x2035, subindex 0x01 - 0x08 */
extern UNS8 PDO38E[8];		/* Mapped at index 0x2036, subindex 0x01 - 0x08 */
extern UNS8 PDO48E[8];		/* Mapped at index 0x2037, subindex 0x01 - 0x08 */
extern UNS8 PDO18F[8];		/* Mapped at index 0x2038, subindex 0x01 - 0x08 */
extern UNS8 PDO28F[8];		/* Mapped at index 0x2039, subindex 0x01 - 0x08 */
extern UNS8 PDO38F[8];		/* Mapped at index 0x203A, subindex 0x01 - 0x08 */
extern UNS8 PDO48F[8];		/* Mapped at index 0x203B, subindex 0x01 - 0x08 */

#endif // HOSTNODE_H
